package com.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-11-20T16:51:43.138+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "HelloEJBBeanService", 
                  wsdlLocation = "http://localhost:8080/HelloEJB/HelloEJBBean?wsdl",
                  targetNamespace = "http://hello.iit.tn/") 
public class HelloEJBBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hello.iit.tn/", "HelloEJBBeanService");
    public final static QName HelloEJBBeanPort = new QName("http://hello.iit.tn/", "HelloEJBBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/HelloEJB/HelloEJBBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloEJBBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/HelloEJB/HelloEJBBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloEJBBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloEJBBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloEJBBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloEJBBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloEJBBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloEJBBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloEJBBeanPort")
    public HelloWS getHelloEJBBeanPort() {
        return super.getPort(HelloEJBBeanPort, HelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloEJBBeanPort")
    public HelloWS getHelloEJBBeanPort(WebServiceFeature... features) {
        return super.getPort(HelloEJBBeanPort, HelloWS.class, features);
    }

}
