package com.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-11-20T16:51:42.936+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://hello.iit.tn/", name = "HelloWS")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWS {

    @WebMethod(operationName = "say_hello")
    @WebResult(name = "return", targetNamespace = "http://hello.iit.tn/", partName = "return")
    public java.lang.String sayHello();
}
